language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master
    - api-v1
    - gh-pages

before_script:
  - npm run build

script:
  - npm test

after_success:
- npm run coverage