language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master
    - api-v1
    - gh-pages

services:
  - postgresql

addons:
  postgresql: "11.2"

after_success:
- npm run coverage