language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master
    - api-v1
    - gh-pages

services:
  - postgresql

dist: trusty

before_script:
  - psql -U postgres -c 'CREATE DATABASE automart_travis_test;'
  - psql -U postgres -c "CREATE USER chuksjoe WITH PASSWORD null;"
  - psql -U postgres -f ./api/v1/db/create-tables.sql -d automart_travis_test

after_success:
- npm run coverage